name: Deploy Backend

on:
  push:
    branches:
      - main  # Change to your actual branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Create .env File  # Inject MongoDB URI from GitHub Secrets
        run: |
          echo "MONGO_URI=$MONGO_URI" >> .env
          echo "PORT=4000" >> .env

      - name: Start Server (Optional - For Debugging)
        run: npm start
